name: DockerFile-Build

on:
    push:
        branches: 
            - main

jobs:
    build:
        name: Build docker image
        runs-on: ubuntu-latest
        steps:
            - name: check out the repository
              uses: actions/checkout@v3

            - name: Habilita Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Log in DockerHub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
            
            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                context: .
                tags: ${{ secrets.IMAGE_NAME }}/my-app:latest
                push: false
            
            - name: Run tests
              uses: addnab/docker-run-action@v3
              with:
                image: ${{ secrets.IMAGE_NAME }}/my-app:latest
                options: --rm
                run: ./run-tests.sh

